imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    
    #Clientes 
    #facebook_client_id: '1265030443545637'
    #facebook_client_secret: 'd3287a9e9bf204d0a3e32d671446c148'
    facebook_client_id: '870589819746939'
    facebook_client_secret: '7ebdc24d72f07919933625cf2448f62f'
    google_client_id: '860655152354-kbdh6pk7inaho4jumi7avadlhur6hajn.apps.googleusercontent.com'
    google_client_secret: '53K9FAd3kgG8tyg2MxcWKK1v'
    
    #Directorios
    Domicilio_directory: '%kernel.root_dir%/../web/uploads/Domicilio'
    PerfilUsuario_directory: '%kernel.root_dir%/../web/uploads/PerfilUsuario'
    Publicacion_directory: '%kernel.root_dir%/../web/uploads/Publicacion'
    
    #Apis
    api_geocode: AIzaSyAViqgnmGUfhNkOox_PAAmHYQuJAn2OpCg
    
    #Firebase
    firebase_url: 'https://fcm.googleapis.com/fcm/send'
    firebase_web_key: 'AAAA0aPv8AQ:APA91bGDBdSCxakNeYLIEI7APONN9Bh3pZ72hzuWuCsOHdCWZ4DbEtxuvv2dmspIYtGiS3DU_ER9rV_KWrPXH0VVqN0yYR5d8bcll8QanbYoegtu0844tX32yJY_RG-jHNqGo2EERvE9'
    
    #Mensajes de error
    no_error: Operacion Realizada Correctamente
    error_db: Error relacionado con la BBDD
    
framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - bootstrap_3_layout.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8mb4 
        unix_socket: /tmp/mysql.sock
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            numeric_functions:
                acos: DoctrineExtensions\Query\Mysql\Acos
                asin: DoctrineExtensions\Query\Mysql\Asin
                atan2: DoctrineExtensions\Query\Mysql\Atan2
                atan: DoctrineExtensions\Query\Mysql\Atan
                bit_count: DoctrineExtensions\Query\Mysql\BitCount
                bit_xor: DoctrineExtensions\Query\Mysql\BitXor
                ceil: DoctrineExtensions\Query\Mysql\Ceil
                cos: DoctrineExtensions\Query\Mysql\Cos
                cot: DoctrineExtensions\Query\Mysql\Cot
                degrees: DoctrineExtensions\Query\Mysql\Degrees
                floor: DoctrineExtensions\Query\Mysql\Floor
                log10: DoctrineExtensions\Query\Mysql\Log10
                pi: DoctrineExtensions\Query\Mysql\Pi
                power: DoctrineExtensions\Query\Mysql\Power
                quarter: DoctrineExtensions\Query\Mysql\Quarter
                radians: DoctrineExtensions\Query\Mysql\Radians
                rand: DoctrineExtensions\Query\Mysql\Rand
                round: DoctrineExtensions\Query\Mysql\Round
                stddev: DoctrineExtensions\Query\Mysql\StdDev
                sin: DoctrineExtensions\Query\Mysql\Sin
                std: DoctrineExtensions\Query\Mysql\Std
                tan: DoctrineExtensions\Query\Mysql\Tan
                variance: DoctrineExtensions\Query\Mysql\Variance

             
#LexikJWTAuthentication
lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'
    
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    spool:     { type: memory }
    encryption: "%mailer_encryption%"
    auth_mode:  "%mailer_auth_mode%"
    host:       "%mailer_host"
    username:   "%mailer_user%"
    password:   "%mailer_password%"

# Nelmio CORS Configuration
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
        hosts: []
        origin_regex: false
 
# FOSRest Configuration
fos_rest:
    disable_csrf_role: ROLE_API
    param_fetcher_listener: true
    view:
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1', 'application/json;version=1.2']
        view_response_listener: 'force'
        formats:
            xml:  true
            json: true
        templating_formats:
            html: true
    format_listener:
        rules:
            - { path: '^/api/', priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
    versioning:
        enabled: true
        resolvers:
            media_type:
                enabled: true
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true
    
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\Usuario
    registration:
        confirmation:
            enabled: true
    from_email:
        address: '%mailer_user%'
        sender_name: 'Click and Eat'
        
#OAuth Login
hwi_oauth:
    #this is my custom user provider, created from FOSUBUserProvider - will manage the 
    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
    #and also, the connecting part (get the token and the user_id)
    connect:
        account_connector: my_user_provider
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_names: [main]
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebook_id
            google: google_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           %facebook_client_id%
            client_secret:       %facebook_client_secret%
            scope:               "email, public_profile"
            infos_url:           "https://graph.facebook.com/me?fields=id,name,email,picture.type(large)"
            paths:
                email: email
            options:
                display: page
        google:
            type:                google
            client_id:           %google_client_id%
            client_secret:       %google_client_secret%
            scope:              "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
            paths:
                email: email