<?php

namespace Proxies\__CG__\AppBundle\Entity\Publicacion;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Publicacion extends \AppBundle\Entity\Publicacion\Publicacion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'horaInicio', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'horaFin', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'plazas', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'precio', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'domicilio', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'foto', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'platos', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'reservas', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'completo', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'descripcion'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'horaInicio', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'horaFin', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'plazas', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'precio', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'domicilio', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'foto', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'platos', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'reservas', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'completo', '' . "\0" . 'AppBundle\\Entity\\Publicacion\\Publicacion' . "\0" . 'descripcion'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Publicacion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraInicio($horaInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraInicio', [$horaInicio]);

        return parent::setHoraInicio($horaInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraInicio', []);

        return parent::getHoraInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraFin($horaFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraFin', [$horaFin]);

        return parent::setHoraFin($horaFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraFin', []);

        return parent::getHoraFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlazas($plazas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlazas', [$plazas]);

        return parent::setPlazas($plazas);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlazas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlazas', []);

        return parent::getPlazas();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecio($precio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecio', [$precio]);

        return parent::setPrecio($precio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecio', []);

        return parent::getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    public function getDomicilio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomicilio', []);

        return parent::getDomicilio();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomicilio($domicilio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomicilio', [$domicilio]);

        return parent::setDomicilio($domicilio);
    }

    /**
     * {@inheritDoc}
     */
    public function setPlatos($platos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlatos', [$platos]);

        return parent::setPlatos($platos);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlatos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlatos', []);

        return parent::getPlatos();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoto', []);

        return parent::getFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFoto($foto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFoto', [$foto]);

        return parent::setFoto($foto);
    }

    /**
     * {@inheritDoc}
     */
    public function addReserva($reserva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReserva', [$reserva]);

        return parent::addReserva($reserva);
    }

    /**
     * {@inheritDoc}
     */
    public function setReservas($reservas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReservas', [$reservas]);

        return parent::setReservas($reservas);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservas', []);

        return parent::getReservas();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompleto($completo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompleto', [$completo]);

        return parent::setCompleto($completo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompleto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompleto', []);

        return parent::getCompleto();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

}
