<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Comentario extends \AppBundle\Entity\Comentario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Comentario' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Comentario' . "\0" . 'usuarioDa', '' . "\0" . 'AppBundle\\Entity\\Comentario' . "\0" . 'usuarioRecibe', '' . "\0" . 'AppBundle\\Entity\\Comentario' . "\0" . 'valoracion', '' . "\0" . 'AppBundle\\Entity\\Comentario' . "\0" . 'puntuacion', '' . "\0" . 'AppBundle\\Entity\\Comentario' . "\0" . 'fechaComentario', '' . "\0" . 'AppBundle\\Entity\\Comentario' . "\0" . 'metadata'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Comentario' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Comentario' . "\0" . 'usuarioDa', '' . "\0" . 'AppBundle\\Entity\\Comentario' . "\0" . 'usuarioRecibe', '' . "\0" . 'AppBundle\\Entity\\Comentario' . "\0" . 'valoracion', '' . "\0" . 'AppBundle\\Entity\\Comentario' . "\0" . 'puntuacion', '' . "\0" . 'AppBundle\\Entity\\Comentario' . "\0" . 'fechaComentario', '' . "\0" . 'AppBundle\\Entity\\Comentario' . "\0" . 'metadata'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Comentario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioDa($usuarioDa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioDa', [$usuarioDa]);

        return parent::setUsuarioDa($usuarioDa);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioDa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioDa', []);

        return parent::getUsuarioDa();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioRecibe($usuarioRecibe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioRecibe', [$usuarioRecibe]);

        return parent::setUsuarioRecibe($usuarioRecibe);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioRecibe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioRecibe', []);

        return parent::getUsuarioRecibe();
    }

    /**
     * {@inheritDoc}
     */
    public function setValoracion($valoracion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValoracion', [$valoracion]);

        return parent::setValoracion($valoracion);
    }

    /**
     * {@inheritDoc}
     */
    public function getValoracion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValoracion', []);

        return parent::getValoracion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPuntuacion($puntuacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPuntuacion', [$puntuacion]);

        return parent::setPuntuacion($puntuacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPuntuacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPuntuacion', []);

        return parent::getPuntuacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaComentario($fechaComentario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaComentario', [$fechaComentario]);

        return parent::setFechaComentario($fechaComentario);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaComentario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaComentario', []);

        return parent::getFechaComentario();
    }

    /**
     * {@inheritDoc}
     */
    public function actualizarFechaComentario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'actualizarFechaComentario', []);

        return parent::actualizarFechaComentario();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetadata($metadata)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetadata', [$metadata]);

        return parent::setMetadata($metadata);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetadata()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetadata', []);

        return parent::getMetadata();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function fromArray($array)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fromArray', [$array]);

        return parent::fromArray($array);
    }

}
